### ISSUE TITLE
Add an option to list contracts/groups/configurations

### ISSUE THREAD

**Issue by lufo0** [akamai/cli-property#1]
The CLI program does not have an option to list the existing contracts, groups nor configurations available under the account for which the credentials have been provided.

If a "more or less" interactive console session is intended, at least listing the above will be needed to avoid having to either know beforehand or check in Luna via web in parallel.

**Comment by synedra** [comment]
I'll add this to the list of items to work on soon (as it will be easy to implement).  We'll probably update the website.js library but create a separate admin script for this functionality, since updateWebSite is designed for operating on a specific property and this is for grabbing metadata.

Sounds like what you'd like is:
* List the groups/contracts
* List the properties (with associated groups/contracts?)
We probably also want to:
* List the products
    -> and then update updateWebSite so it takes a --product flag instead of "guessing" based on the account

Would you like to also:
* List the hostnames?  This could be a big list unless you give some sort of search parameter.  We could have you give contract/group and then get the hostnames/products in that way.

Would that meet the goals you have, or are there other pieces you'd like to see?

Thanks,
Kirsten

**Comment by lufo0** [comment]
Dear Kirsten:

Sorry for the delay in this reply, I have been travelling last week and
then the message got buried in the the inbox.

In summary, yes, these would be the functionalities I would most likely
need in order to operate on configurations. As you can see, these are
oriented to "reaching" the rigth property without the need to know the
requested details (Contracts, Groups, Property Names...) without the
need to knowing them in advance.

I don't see an absolute need to list hostnames, as I understood from the
docs that the opposite (selecting the config by stating the the desired
hostname) is available, and from my own experience "hostname" is the
information we usually know.

This of course mostly makes sense for interactive CLI sessions and/or
applications with discovery of the existing configurations, not any
batch interaction programmed in advance.

I will try to find some time for doing further exploration in the
upcoming days, and keep an eye on the repo.

BTW I will be at the Akamai Krakow office next week (Mon to Fri), just
in case it is of any use.

Best regards,

Luciano Lemberg - Chief Technology Executive

Milloh CS / Akamai NetAlliance Partner

E: luciano@milloh-cs.com / M: +34 620 79 80 49 / Skype: l_lemberg


-- Kirsten Hunter (02/05/2017 1:41):
