### ISSUE TITLE
Update property creates a new version every time

### ISSUE THREAD

**Issue by ghost** [akamai/cli-property#20]
Flag not to create a new version, --version flag for a specific one

**Comment by RKPrabhu100** [comment]
Hey,

I tried using the --version flag however, It always creates a new version.

Eg commands 
1) akamai property update RK_TestAPI --version 1 --file rules.json
Result - Version unknown.
2) akamai property update RK_TestAPI --version --file rules.json
Result - Version unknown.

Could you please let me know the format in order to update a specific version and not create a new version?

**Comment by synedra** [comment]
I'll look into this shortly.

**Comment by RKPrabhu100** [comment]
Thanks Kirsten!

Also, I was wonder if we could add the command option "--file" for modify just like how we have for update. This way we can upload the entire JSON but not create a new version unless needed with only 1 command. My guesses are there is minimal change in the code base, but you could correct me otherwise.

Regards,
RK Prabhu

**Comment by synedra** [comment]
The idea of “modify” is to make quick little changes to the property, not to upload the entire JSON.  The right behavior is for update to allow you to not create a new version, which I’ll work on.

Kirsten

**Comment by RKPrabhu100** [comment]
Thanks for adding clarity Kirsten!
