### ISSUE TITLE
deactivate delete opt-in

### ISSUE THREAD

**Issue by ghost** [akamai/cli-property#44]

**Comment by javiergarza** [comment]
I hit this today. Can't delete a file which has not been activated
To reproduce:
1) create a property using "akamai property create <new_property> --clone <existing_property>"
2) Try to delete new property using: "akamai property delete <new_property>

Here is the output:
akamai property delete JavierGarza-20180911.world-tour
... searching propertyName for JavierGarza-20180911.world-tour
... getting info for prp_485529
Deactivating JavierGarza-20180911.world-tour to STAGING
... deactivating property (JavierGarza-20180911.world-tour) v1 on STAGING
ERROR:  {
  "type" : "https://problems.luna.akamaiapis.net/papi/v0/deactivation/not-active-in-staging",
  "title" : "Property not active in STAGING",
  "status" : 422,
  "detail" : "The property cannot be deactivated because it is not active in STAGING.",
  "instance" : "https://akab-n33lt5hyp5evdhvg-cmh6fsmfmc67t3w2.luna.akamaiapis.net/papi/v1/properties/prp_485529/activations?contractId=ctr_C-1FRYVV3&groupId=grp_123081#65b2ffcf-92ad-429e-b64d-1c3454bbb631"
}
{
  "type" : "https://problems.luna.akamaiapis.net/papi/v0/deactivation/not-active-in-staging",
  "title" : "Property not active in STAGING",
  "status" : 422,
  "detail" : "The property cannot be deactivated because it is not active in STAGING.",
  "instance" : "https://akab-n33lt5hyp5evdhvg-cmh6fsmfmc67t3w2.luna.akamaiapis.net/papi/v1/properties/prp_485529/activations?contractId=ctr_C-1FRYVV3&groupId=grp_123081#65b2ffcf-92ad-429e-b64d-1c3454bbb631"
}

**Comment by favroom** [comment]
I was attending the Akamai Developer World Tour in Amsterdam today and stumbled upon the same issue...
I tried to get some more info by adding --debug to the command, but that didn't reveal any helpfull info...
