### ISSUE TITLE
Unable to create a new property

### ISSUE THREAD

**Issue by akamath9** [akamai/cli-property#48]
akamai property create www.clitestakamath.com --group <....>  --contract <......>
Creating new property www.clitestakamath.com
EdgeHostname should be included as new edge hostnames take several minutes to appear.
... retrieving list of Group Ids
... retrieving list of Products for this contract
ERROR:  {}
TypeError: Cannot read property 'groupId' of undefined
    at _getPropertyInfo.then.data (/Users/akamath/.akamai-cli/src/cli-property/src/website.js:2173:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by synedra** [comment]
What product is on the group/contract?  Only certain products are included (I need to improve the error handling).  I can add another product if you need it.

**Comment by akamath9** [comment]
Hi Kirsten,

Below is the command I used and found that the issue persists only for the
below group and contract for Ion Standard Beta Jam Account.


akamai property create www.clitestakamath.com --group grp_48678 --contract
ctr_3-16U20BL


When i tried the same using New Hire Account with below parameters i was
able to create the config.


akamai property create akamathtest_pm --group 54705 --contract C-119ZAFW

Thank you for your quick response. If I face any other issues while using
CLI i will update you.

Thanks & Regards
Ananth Kamath

**Comment by synedra** [comment]
I will see what I can do about the product issue, this needs a better solution than what I have.  Thanks for the feedback, and I'll update this issue when I get the issue resolved.

**Comment by akamath9** [comment]
Sure, Thank you Kirsten.

**Comment by jeffolsonatnfm** [comment]
I have been battling the same error also.  It seems like it is a lie-ing error message.  Because the groupId is being passed in.  I can clone just fine, but a fresh create always fails with this error, no matter which version/environment of the API I use.

**Comment by synedra** [comment]
What is the product for that group?  It's almost certainly that.  I can add it to the list of delivery products and it will work.

Kirsten

Sent from my iPhone

On Jan 25, 2018, at 11:12 AM, jeffolsonatnfm <notifications@github.com<mailto:notifications@github.com>> wrote:


I have been battling the same error also. It seems like it is a lie-ing error message. Because the groupId is being passed in. I can clone just fine, but a fresh create always fails with this error, no matter which version/environment of the API I use.

-

**Comment by jeffolsonatnfm** [comment]
Thank you for the response.  It is probably the product as you say.  We had a conversation with the automation group at Akamai today, and they recommended first doing a clone then an update in our automation instead of fresh creates.  Instead of a template file, we are creating a template property, cloning this, and then retrieving it to a file that we will then modify for the update.
