### ISSUE TITLE
Please document .edgerc sections as they relate to API Authorizations

### ISSUE THREAD

**Issue by dhambali** [akamai/cli-property#55]
[alerts], [ccu], [papi], [default] are commonly known.

I've been able to discover [billingusage], [billingcenter], [cloudlet], [live], and [gtm] by looking through some python scripts.

Is there a document that shows the relationship of .edgerc sections to each service name in API Authorizations?

![image](https://user-images.githubusercontent.com/1854558/35592315-6ec4f22e-05c1-11e8-8736-d37cfce89117.png)

**Comment by synedra** [comment]
Hi!

This really belongs more as a "cli" issue rather than a "cli/property" issue.  While I do need to get a better note in the help for cli-property, it's not going to solve the greater issue.

The CLI programs will have a microsite with this type of information on it in the next few months.  The Python scripts are separate, and really simply pick something that makes sense for the code at hand.

There's no "right" set of strings for non-CLI implementations.  You can use what makes sense to you and change the code accordingly.

Even when we have a CLI document, it'll just show what *we* have chosen to use for credentials.  You can always override with a --section indicator.

Thanks,
Kirsten



On January 30, 2018 at 1:28:58 PM, dhambali (notifications@github.com<mailto:notifications@github.com>) wrote:

[alerts], [ccu], [papi], [default] are commonly known.

I've been able to discover [billingusage], [billingcenter], [cloudlet], [live], and [gtm] by looking through some python scripts.

Is there a document that shows the relationship of .edgerc sections to each service name in API Authorizations?

[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_1854558_35592315-2D6ec4f22e-2D05c1-2D11e8-2D8736-2Dd37cfce89117.png&d=DwMCaQ&c=96ZbZZcaMF4w0F4jpN6LZg&r=Q1_WK8mWWUtQ5xZX1lcsIPCasN7Y3hsyzvEZltDs4Vs&m=Bh-tYRVumCpmCMtT5xw9gpoRNVL2QVcQuo5oEAKaaoU&s=-FtzHM3X3lhujmLJcrCxhqfhuES95KfIEDHDcr1cnhE&e=>

**Comment by dhambali** [comment]
No problem.  I will close out, and open a new issue in CLI.
