### ISSUE TITLE
'--hostnames' argument returns exception

### ISSUE THREAD

**Issue by dmcallis1** [akamai/cli-property#63]
Recently, a pipeline job which creates a new property began failing. It appears the '--hostnames' argument is not working, and even with debug option enables I cannot identify the root cause.

**Command**
akamai property create devopstest-qa-61.gcs.com --clone devopstest-gold.gcs.com --hostnames devopstest-qa-61.gcs.com --origin akshay-r13.000webhostapp.com

**Output**
... searching propertyName for devopstest-gold.gcs.com
... getting info for prp_399297
... retrieving clone info
... retrieving clone rules for cpcode
Creating property config devopstest-qa-61.gcs.com
Retrieving devopstest-qa-61.gcs.com v1
... retrieving property (devopstest-qa-61.gcs.com) v1
... updating property (devopstest-qa-61.gcs.com) v1
... retrieving list of hostnames {ctr_C-1ED34DY : grp_63802 : prp_439248}
Updating property hostnames
Adding hostname devopstest-qa-61.gcs.com
ERROR:  Unable to assign hostname.  Please try to add the hostname in 30 minutes using the --addhosts flag.
Unable to assign hostname.  Please try to add the hostname in 30 minutes using the --addhosts flag.

**Comment by synedra** [comment]
I'll look at this as soon as I'm online.

K

Sent from my iPhone

On Feb 7, 2018, at 12:52 PM, Duncan McAllister <notifications@github.com<mailto:notifications@github.com>> wrote:


Recently, a pipeline job which creates a new property began failing. It appears the '--hostnames' argument is not working, and even with debug option enables I cannot identify the root cause.

Command
akamai property create devopstest-qa-61.gcs.com<http://devopstest-qa-61.gcs.com> --clone devopstest-gold.gcs.com<http://devopstest-gold.gcs.com> --hostnames devopstest-qa-61.gcs.com<http://devopstest-qa-61.gcs.com> --origin akshay-r13.000webhostapp.com<http://akshay-r13.000webhostapp.com>

Output
... searching propertyName for devopstest-gold.gcs.com<http://devopstest-gold.gcs.com>
... getting info for prp_399297
... retrieving clone info
... retrieving clone rules for cpcode
Creating property config devopstest-qa-61.gcs.com<http://devopstest-qa-61.gcs.com>
Retrieving devopstest-qa-61.gcs.com<http://devopstest-qa-61.gcs.com> v1
... retrieving property (devopstest-qa-61.gcs.com<http://devopstest-qa-61.gcs.com>) v1
... updating property (devopstest-qa-61.gcs.com<http://devopstest-qa-61.gcs.com>) v1
... retrieving list of hostnames {ctr_C-1ED34DY : grp_63802 : prp_439248}
Updating property hostnames
Adding hostname devopstest-qa-61.gcs.com<http://devopstest-qa-61.gcs.com>
ERROR: Unable to assign hostname. Please try to add the hostname in 30 minutes using the --addhosts flag.
Unable to assign hostname. Please try to add the hostname in 30 minutes using the --addhosts flag.

-

**Comment by synedra** [comment]
Hi Duncan,

I need a little more help on this one, could you please send me info on the account (and potentially credentials) via email?  I'm not seeing it on our account with a similar command

**Comment by synedra** [comment]
MacBook-Pro-2:python khunter$ akamai property create testhostnames.example.com --clone sandbox.akamaideveloper.com --hostnames testing.example.com --origin bc.akamaiapibootcamp.com
... searching propertyName for sandbox.akamaideveloper.com
... getting info for prp_428260
... retrieving clone info
... retrieving clone rules for cpcode
Creating property config testhostnames.example.com
Retrieving testhostnames.example.com v1
... retrieving property (testhostnames.example.com) v1
... updating property (testhostnames.example.com) v1
... retrieving list of hostnames {ctr_C-1FRYVV3 : grp_111340 : prp_439417}
Updating property hostnames
Adding hostname testing.example.com
Command time: 0.57 mins

**Comment by dmcallis1** [comment]
Quick update- the command started working when I used a different clone target….. 

jenkins@ip-10-0-1-60:~$ akamai property create devopstest-qa-tt.gcs.com --clone dm-lab.akamaized.net --hostnames devopstest-qa-tt.gcs.com --origin akshay-r13.000webhostapp.com
... searching propertyName for dm-lab.akamaized.net
... getting info for prp_384899
... retrieving clone info
... retrieving clone rules for cpcode
Creating property config devopstest-qa-tt.gcs.com
Retrieving devopstest-qa-tt.gcs.com v1
... retrieving property (devopstest-qa-tt.gcs.com) v1
... updating property (devopstest-qa-tt.gcs.com) v1
... retrieving list of hostnames {ctr_C-1ED34DY : grp_63802 : prp_439496}
Updating property hostnames
Adding hostname devopstest-qa-tt.gcs.com
Command time: 1.2 mins
