### ISSUE TITLE
'modify' statement does not support multiple arguments

### ISSUE THREAD

**Issue by dmcallis1** [akamai/cli-property#77]
Using the 'akamai property modify' statement with 2 modify arguments (--cpcode and --notes) is not working as expected. When used with only one argument, the statement works as expected (either modifies CP Code or Notes)... when both arguments are used, only the '--notes' value is evaluated.

**Comment by joaquin-gimenez** [comment]
@dmcallis1  @synedra @dshafik The options related to the version are: new, propver, notes, variables, addhosts, delhosts, edgehostname, origin, forward, sureroutemap, surerouteto, sureroutehost. I'm thinking if the --new option is provided, all the rest of the options will be applied to the new version created. Except if a --propver is provided all options except --new are going to be executed against the --propver, and not the --new version.
I would like your opinions on this scenario to make sure it's the correct one as It's a big change.

**Comment by synedra** [comment]
That sounds right.

Note that when making this change (or any change) I’d love for tests to be added/updated to include the new functionality.

Thanks,
Kirsten

**Comment by joaquin-gimenez** [comment]
@synedra thanks for the response,
In this particular case that all the big changes are going to be done on the command interface (akamaiProperty) do you think I should mock the response for the tests or go against the server?

**Comment by dshafik** [comment]
Maybe I read this wrong, but if *both* are provided, I would expect that a NEW version of the property is created, _based on_ the version specified with `--propver` (instead of the latest), and the changes would **then** be applied to the _new_ version.

From what you wrote, it sounds more like you're thinking to modify the `--propver` version (which may be immutable) and _then_ create a new version from it, this wouldn't be the right behavior.

**Comment by joaquin-gimenez** [comment]
@dshafik makes sense, I'll take it into account.
thanks

**Comment by synedra** [comment]
Oh, great catch Davey.  Yes, this is how it should work.

K

Sent from my iPhone

On Jan 9, 2019, at 10:11 AM, Davey Shafik <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe I read this wrong, but if both are provided, I would expect that a NEW version of the property is created, based on the version specified with --propver (instead of the latest), and the changes would then be applied to the new version.

From what you wrote, it sounds more like you're thinking to modify the --propver version (which may be immutable) and then create a new version from it, this wouldn't be the right behavior.
