### ISSUE TITLE
modify --variable does not work

### ISSUE THREAD

**Issue by ericdebeij** [akamai/cli-property#84]
The following sequence of commands (replace PROPERTY with the property of your choice):
akamai property retrieve PROPERTYNAME --variables >var.txt
akamai property modify PROPERTYNAME --variables var.txt

Returns with the following error message:
ERROR:  TypeError: Cannot read property 'map' of undefined
    at data.map.variable (/Users/hdebeij/.akamai-cli/src/cli-property/src/website.js:1956:37)
    at Array.map (<anonymous>)
    at Promise.then.then.then.data (/Users/hdebeij/.akamai-cli/src/cli-property/src/website.js:1955:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Tried with multiple properties.
(node v10.11.0)

Work-around: update the config itself.

**Comment by joaquin-gimenez** [comment]
@synedra @dshafik The issue is that on retrieve it does not save an action to the file, and I guess that behavior is correct so I'm thinking of logging a message as the one attached.

![screen shot 2019-01-22 at 12 46 21 pm](https://user-images.githubusercontent.com/1648222/51546882-e4190d80-1e43-11e9-96fb-c3089eb5a388.png)
